name: efAdminTag
version: 1.0.1
main: me.cynadyde.efadmintag.EfAdminTagPlugin
description: Allows staff to toggle their staff permissions.
author: Cynadyde
depend:
  - LuckPerms
commands:
  admintag:
    description: toggles staff permissions
